name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  login:
    runs-on: ubuntu-latest
    steps: 
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com'
          privateKey: ${{ secrets.HP_DEMO}}
      
Upload_S3:
    runs-on: ubuntu-latest
            needs: login
            steps:
            - name: Check the  branch
              uses: actions/checkout@v2 
            - name: Dist download
            - run: scp -i ubuntu-geppetto.pem -r ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com:/home/ubuntu/hpsiva/dist/quoteomatictest .    