name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Dist:
    runs-on: ubuntu-latest
    steps: 
#       - name: Download
#         uses: JimCronqvist/action-ssh@master
      - name: demo
        run: mkdir test
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com'
          privateKey: ${{ secrets.KEY}}      
          command: |
            cd hp_wordpress
            git pull https://github.com/dan-castillo/nissan-demo.git
            git checkout feature/wordpress_deploy
            git branch
         
  # Upload_S3:
  #   runs-on: ubuntu-latest
  #   needs: login
  #   steps:
      # - name: Dist download
      #   run:
      #     scp -i ubuntu-geppetto.pem -r ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com:/home/ubuntu/hpsiva/dist/quoteomatictest .    
