name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Dist:
    runs-on: ubuntu-latest
    steps: 
      # - name: Download
      #   uses: JimCronqvist/action-ssh@master
#       - name: demo
#         run: mkdir test
      - name: Dist download
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
        with:
          source: "/home/runner/work/hpdemo/hpdemo"
          target: "/home/ubuntu/hpsiva/dist/quoteomatictest"  
          strip_components: 1
          # command: |
          #   # docker ps -a   
          #   ls   
          #   scp -i  ${{ secrets.HP_DEMO}} -r ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com:/home/ubuntu/hpsiva/dist/quoteomatictest . 
            
  # Upload_S3:
  #   runs-on: ubuntu-latest
  #   needs: login
  #   steps:
      # - name: Dist download
      #   run:
      #     scp -i ubuntu-geppetto.pem -r ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com:/home/ubuntu/hpsiva/dist/quoteomatictest .    
