name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  HP:
    runs-on: ubuntu-latest
    steps: 
#       - name: Download
#         uses: JimCronqvist/action-ssh@master
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com'
          privateKey: ${{ secrets.KEY}}      
          command: |
            cd hp_wordpress
            cd nissan-demo
            git init
            git pull git@github.com:dan-castillo/nissan-demo.git
            git checkout feature/wordpress_deploy
            ls
            cd application/client/desktop/quoteomatictest
            docker build -t newquoteui-hpnew .
            docker run --name quoteomaticui-hpnew --restart=unless-stopped -d -p 5080:5000 -v new-hp:/app newquoteui-hpnew
            cd ../../../
            cd services/custom_services/wcmx-wordpress
            docker build -t wordpressmanager-hp .
            docker run --name wordpressmanager-hp --restart=unless-stopped -d -p 3099:3013 -v new-hp:/code --env-file=../../.env wordpressmanager-hp
            cd ..
            cd cdnmanager
            docker build -t cdnmanager-hp .
            docker run --name cdnmanager-hp --restart=unless-stopped -d -p 3097:3111 -v new-hp:/code --env-file=../../.env --link wordpressmanager-hp cdnmanager-hp
            docker ps -a
         
  # Upload_S3:
  #   runs-on: ubuntu-latest
  #   needs: login
  #   steps:
      # - name: Dist download
      #   run:
      #     scp -i ubuntu-geppetto.pem -r ubuntu@ec2-34-197-46-177.compute-1.amazonaws.com:/home/ubuntu/hpsiva/dist/quoteomatictest .    
